[workspace]
members = [
    "nyx-core",
    "nyx-crypto",
    "nyx-transport",
    "nyx-mix",
    "nyx-fec",
    "nyx-stream",
    "nyx-telemetry", # Prometheus exporter crate
    "nyx-control",
    "nyx-cli",
    "nyx-daemon",
    "nyx-sdk",
    "nyx-sdk-wasm",
    "nyx-conformance",
    "nyx-mobile-ffi", # Mobile platform FFI bindings
    "build-protoc",
]
resolver = "2"

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = "z" 

# Reduce link-time memory usage for tests on Windows/MSVC by disabling debug symbols
# and minimizing object fragmentation.
[profile.test]
debug = 0
codegen-units = 1
opt-level = 0
