apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nyx.fullname" . }}
  labels:
    app: {{ include "nyx.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "nyx.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "nyx.name" . }}
    spec:
      containers:
        - name: nyxd
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 43300
            - containerPort: {{ .Values.exporter.port }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          livenessProbe:
            tcpSocket:
              port: 43300
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /metrics
              port: {{ .Values.exporter.port }}
            initialDelaySeconds: 5
            periodSeconds: 10 