{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "nyx.fullname" . }}
  labels:
{{ include "nyx.labels" . | indent 4 }}
spec:
  podSelector:
    matchLabels:
{{ include "nyx.selectorLabels" . | indent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
      {{- range .Values.networkPolicy.allowIngressFromNamespaces }}
      - namespaceSelector:
{{ toYaml .namespaceSelector | indent 10 }}
      {{- end }}
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
        - protocol: TCP
          port: {{ .Values.service.metricsPort }}
  egress:
    - to:
      {{- if .Values.networkPolicy.allowEgressDNS }}
      - namespaceSelector: {}
        ports:
          - protocol: UDP
            port: 53
          - protocol: TCP
            port: 53
      {{- end }}
{{- with .Values.networkPolicy.additionalIngressRules }}
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- with .Values.networkPolicy.additionalEgressRules }}
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}


