{{- if and .Values.secrets.create (not (empty .Values.secrets.apiTokenValue)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (printf "%s-secret" (include "nyx.fullname" .)) .Values.secrets.name }}
  labels:
{{ include "nyx.labels" . | indent 4 }}
type: Opaque
stringData:
  {{ .Values.secrets.apiTokenKey }}: {{ .Values.secrets.apiTokenValue | quote }}
{{- end }}


