apiVersion: v1
kind: Service
metadata:
  name: {{ include "nyx.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "nyx.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 43300 