[package]
name = "nyx-crypto"
version = "0.1.0"
edition = "2021"

description = "Nyx cryptography engine implementing Noise_Nyx handshake and HKDF wrappers."
license = "MIT OR Apache-2.0"

[features]
# Enable post-quantum Kyber fallback.
pq = ["pqcrypto-kyber", "pqcrypto-traits"]
bench = ["criterion", "criterion-cmp"]

[dependencies]
x25519-dalek = "2.0"
blake3 = { version = "1.5", features = ["pure"] }
sha2 = "0.10"
hkdf = "0.12"
rand_core = { version = "0.6", features = ["getrandom"] }
pqcrypto-kyber = { version = "0.7", optional = true, package = "pqcrypto-kyber" }
pqcrypto-traits = { version = "0.3", optional = true, package = "pqcrypto-traits" }

[dev-dependencies]
hex-literal = "0.4"
zeroize = { version = "1", features=["zeroize_derive"] }
criterion = { version = "0.5", optional = true }
criterion-cmp = { version = "0.4", optional = true }
