[package]
name = "nyx-crypto"
version = "0.1.0"
edition = "2021"

description = "Nyx cryptography engine implementing Noise_Nyx handshake and HKDF wrappers."
license = "MIT OR Apache-2.0"

[features]
# Enable post-quantum Kyber fallback.
pq = ["pqcrypto-kyber", "pqcrypto-traits"]
# Build with ONLY PQ algorithm (disable X25519). Implies pq.
pq_only = ["pq"]
bench = ["criterion"]
hybrid = ["pq"]

[dependencies]
x25519-dalek = "2.0"
blake3 = { version = "1.5", features = ["pure"] }
sha2 = "0.10"
hkdf = "0.12"
rand_core = { version = "0.6", features = ["getrandom"] }
criterion = { version = "0.5", optional = true }
zeroize = { version = "1", features=["zeroize_derive"] }
pqcrypto-traits = { version = "0.3", optional = true, package = "pqcrypto-traits" }

[target.'cfg(not(target_os = "windows"))'.dependencies]
pqcrypto-kyber = { version = "0.7", optional = true, package = "pqcrypto-kyber" }

[target.'cfg(windows)'.dependencies]
pqcrypto-kyber = { version = "0.7", optional = true, package = "pqcrypto-kyber", default-features = false, features = ["no_simd"] }

[dev-dependencies]
hex-literal = "0.4"
