replicaCount: 1

image:
  repository: ghcr.io/nyxproject/nyxd
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 43300

# Prometheus exporter port used for readiness probe
exporter:
  port: 9090

# PodDisruptionBudget configuration
pdb:
  enabled: true
  minAvailable: 1

# HorizontalPodAutoscaler configuration
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75
  targetBytesPerSecond: "5Mi"

# Pod security context (seccomp)
podSecurity:
  # Localhost seccomp profile name mounted via projected volume or node default path
  seccompProfile: "nyx-seccomp-bpf.json"

# Default resource requests/limits (can be overridden)
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi 