[package]
name = "nyx-cli"
version = "0.1.0"
edition = "2021"

description = "Nyx command line interface utilities"
license = "MIT OR Apache-2.0"

[dependencies]
clap = { version = "4", features = ["derive"] }
reqwest = { version = "0.12", default-features = false, features = ["blocking", "rustls-tls"] }
regex = "1.10"
anyhow = "1" 
rand = "0.8"
zeroize = "1.7"
nyx-crypto = { path = "../nyx-crypto" }
rpassword = "7.2"
dirs = "5"
fluent-bundle = { version = "0.16" }
unic-langid = "0.9" 
once_cell = "1.19"

# gRPC client dependencies
tonic = { version = "0.10", features = ["transport"] }
prost = "0.12"
prost-types = "0.12"

# Networking and async runtime
tokio = { version = "1.37", features = ["full"] }
tokio-stream = "0.1"

# Benchmarking and performance measurement
indicatif = "0.17"
humantime = "2.1"
byte-unit = "5.1"

# Enhanced CLI features
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
colored = "2.1"
comfy-table = "7.1"

[build-dependencies]
tonic-build = "0.10" 