name: ChaosMesh Latency Test

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  chaos-latency:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Setup KinD
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: v0.22.0
          config: |
            kind: Cluster
            apiVersion: kind.x-k8s.io/v1alpha4
            nodes:
            - role: control-plane
            - role: worker
      - name: Install Chaos Mesh
        run: |
          kubectl apply -f https://mirrors.chaos-mesh.org/v2.6.2/crd.yaml
          kubectl apply -f https://mirrors.chaos-mesh.org/v2.6.2/chaos-mesh.yaml
          kubectl wait --for=condition=available --timeout=180s -n chaos-mesh deploy/chaos-controller-manager
      - name: Inject 200ms Latency to all pods
        run: |
          cat <<EOF | kubectl apply -f -
          apiVersion: chaos-mesh.org/v1alpha1
          kind: NetworkChaos
          metadata:
            name: inject-latency
            namespace: default
          spec:
            action: delay
            mode: all
            delay:
              latency: '200ms'
            duration: '15s'
          EOF
      - name: Run Workspace Tests Under Chaos
        run: cargo test --workspace --all-features -- --skip slow 