name: NyxNet CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Workspace tests
        run: cargo test --workspace --all-features --no-fail-fast

      - name: Daemon metrics tests (experimental-metrics)
        run: cargo test -p nyx-daemon --features experimental-metrics --tests --no-fail-fast

      - name: Daemon OTLP exporter smoke
        run: cargo test -p nyx-daemon --features experimental-metrics,otlp_exporter --tests --no-fail-fast
        env:
          NYX_OTLP_ENABLED: "0"

      - name: CLI alerts smoke
        run: |
          cargo build -p nyx-cli --tests
          cargo test -p nyx-cli --test alerts_cmd --no-fail-fast

      - name: Mobile FFI telemetry (build only)
        run: |
          cargo build -p nyx-mobile-ffi --features telemetry

      - name: Add wasm32 target
        run: rustup target add wasm32-unknown-unknown

      - name: nyx-sdk-wasm tests (node)
        run: cargo test -p nyx-sdk-wasm --target wasm32-unknown-unknown --no-fail-fast

name: Nyx CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        features: ["", "pq", "pq_only"]
    name: cargo test (${{ matrix.os }}, features="${{ matrix.features }}")
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
      - name: Build & Test
        run: |
          if [ "${{ matrix.features }}" = "" ]; then
            cargo test --all --all-features
          else
            cargo test --all --no-default-features --features "${{ matrix.features }}"
          fi
        shell: bash 

  wasm-build:
    runs-on: ubuntu-latest
    name: wasm32 build
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust (wasm target)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown
          override: true
      - name: Build nyx-sdk-wasm
        run: |
          cargo build -p nyx-sdk-wasm --target wasm32-unknown-unknown --release 