name: docs

on:
  push:
    branches: [ main ]
    paths:
      - "proto/**.proto"
      - "spec/**"
      - "docs/**"
      - "mkdocs.yml"

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install protoc-gen-doc
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler-grpc
      - name: Generate gRPC HTML
        run: |
          mkdir -p docs/api
          for f in $(find proto -name '*.proto'); do
            protoc -I proto --doc_out=html,api.html:docs/api $f
          done
      - name: Build MkDocs site
        uses: amitsingh-007/markdown-to-html@v3
        with:
          input_dir: docs
          output_dir: site
      - name: Deploy to Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site 